##-----------服务基本信息配置-------------------##
spring:
  profiles:
    include: redis,datasource,admin,mybatis
  application:
    #服务的名字
    name: journey-system-app
##-----------tomcat配置-------------------##
server:
  session-timeout: 60
  tomcat.uri-encoding: UTF-8
  port: 8090
  servlet:
    context-path: /
##-----------关闭安全验证-------------------##
management:
  endpoints:
    web:
      exposure:
        include: "*"



