##-----------服务基本信息、数据源配置-------------------##
spring:
  application:
    name: journey-system-app #服务的名字
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://10.200.47.70:3306/journey_system_app?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      stat-view-servlet.allow: true
##-----------redis配置-------------------##
redis:
  database: 0 # Redis数据库索引（默认为0）
  host: 127.0.0.1  #Redis服务器地址
  port: 6379 # Redis服务器连接端口
  password: # Redis服务器连接密码（默认为空）
  pool:
    max-active: 20 # 连接池最大连接数（使用负值表示没有限制）
    max-idle: 10 # 连接池中的最大空闲连接
    max-wait: 1000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    min-idle: 5 # 连接池中的最小空闲连接
    timeout: 2000 # 连接超时时间（毫秒）
##-----------tomcat配置-------------------##
server:
  session-timeout: 60
  tomcat.uri-encoding: UTF-8
##-----------mybatis映射配置-------------------##
mybatis:
  type-aliases-package: com.cmrh.journey.system.app.pojo
  mapper-locations: classpath:mapper/*.xml
mapper:
  mappers: com.cmrh.journey.system.utils.dao.MyMapper
  not-empty: false
  identity: MYSQL
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true



